import type { Metadata } from "next";
import "./globals.css";
import { getLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "Codebusters App",
  description: "Generated by Devstock app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
